fix: 🐛 vessel verify fails (#13)
* Update README.md

The `base` dependency needs to be added, otherwise `vessel verify` fails with this error message when cap is used in another project:
```
Failed to verify "cap" with:
.vessel/cap/v1.0.4/src/Cap.mo:23.1-23.43: import error [M0010], package "base" not defined
.vessel/cap/v1.0.4/src/Cap.mo:24.1-24.29: import error [M0010], package "base" not defined
.vessel/cap/v1.0.4/src/Cap.mo:25.1-25.29: import error [M0010], package "base" not defined
.vessel/cap/v1.0.4/src/Cap.mo:26.1-26.29: import error [M0010], package "base" not defined
.vessel/cap/v1.0.4/src/Cap.mo:27.1-27.31: import error [M0010], package "base" not defined
.vessel/cap/v1.0.4/src/Cap.mo:28.1-28.33: import error [M0010], package "base" not defined
.vessel/cap/v1.0.4/src/Cap.mo:29.1-29.37: import error [M0010], package "base" not defined
.vessel/cap/v1.0.4/src/Cap.mo:30.1-30.31: import error [M0010], package "base" not defined

Error: Failed to verify: ["cap"]
```

* Update package-set.dhall

added `base` dependency for the example